name: Deplo CI/CD

on: 
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]
  
env:
  TEST_EVENT_DATA: ${{ toJson(github) }}
jobs:
  job1:
    name: Start CI
    runs-on: ubuntu-latest
    container: docker:20.10
    steps:
      - name: output event payload
        run: |
          echo "TEST_EVENT_DATA=[$TEST_EVENT_DATA]"
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ runner.os }}-${{ github.sha }}
          restore-keys:
            deplo-git-v1-${{ runner.os }}-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Touch file
        run: cat README.md | md5sum > checksum.txt
      - name: show hosts
        working-directory: /etc
        run: cat hosts
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checksum
          path: |
            checksum.txt
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
  job2:
    name: Start CI2
    needs: job1
    runs-on: ubuntu-latest
    container: docker:20.10
    steps:
      - name: Fetch repository cache
        id: fetch-repository-cache
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ runner.os }}-${{ github.sha }}
          restore-keys:
            deplo-git-v1-${{ runner.os }}-
      - name: Checkout
        if: steps.fetch-repository-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          # deplo needs to refer previous commit of current HEAD to determine diff
          fetch-depth: 2
      - name: Restore repository from cache
        if: steps.fetch-repository-cache.outputs.cache-hit == 'true'
        run: git reset --hard HEAD
      - name: Download checksum
        uses: actions/download-artifact@v2
        with:
          name: checksum
      - name: touch file
        run: |
          if [ "$(cat checksum.txt)" = "$(cat README.md | md5sum)" ]; then
            echo "ok"
          else
            echo "ng"
            exit 1
          fi
      - name: show diff
        run: |
          echo "===== diff start ====="
          git --no-pager diff HEAD^..HEAD
          echo "===== diff end ====="
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
