name: Deplo CI/CD

on: 
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]
  
jobs:
  job1:
    name: Start CI
    runs-on: ubuntu-latest
    steps:
      - name: Cache repository
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          restore-keys:
            deplo-git-v1-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
            deplo-git-v1-${{ runner.os }}-${{ github.ref }}-
            deplo-git-v1-${{ runner.os }}-
      - name: Checkout
        if: steps.cache-repository.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
      - name: Touch file
        run: cat README.md | md5sum > checksum.txt
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checksum
          path: |
            checksum.txt
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
  job2:
    name: Start CI2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Cache repository
        uses: actions/cache@v2
        with:
          path: .git
          key: deplo-git-v1-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          restore-keys:
            deplo-git-v1-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
            deplo-git-v1-${{ runner.os }}-${{ github.ref }}-
            deplo-git-v1-${{ runner.os }}-
      - name: Checkout
        if: steps.cache-repository.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
      - name: Download checksum
        uses: actions/download-artifact@v2
        with:
          name: checksum
      - name: touch file
        run: |
          if [ "$(cat checksum.txt)" = "$(cat README.md | md5sum)" ]; then
            echo "ok"
          else
            echo "ng"
            exit 1
          fi
      - name: show diff
        run: |
          echo "===== diff start ====="
          git --no-pager diff HEAD^..HEAD
          echo "===== diff end ====="
      - name: Setup ssh session to debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
